#!/usr/bin/env bash

clip-youtube(){
    pushd /tmp
    youtube-dl --write-auto-sub --embed-subs --no-continue $1 -o tmp_vid.mp4 -f mp4
    clip-file tmp_vid.mp4
    popd
}

# TODO better naming
make-youtube-clip(){
    while getopts "ls" o; do
        case "$o" in
            l) ffmpeg_length=1
               echo "LENGTH BASED"
               ;;
            s) localsubs=1
               ;;
        esac
    done
    URL=${@:$OPTIND:1}
    START=${@:$OPTIND+1:1}
    END_OR_LENGTH=${@:$OPTIND+2:1}
    case $1 in
        "") echo -e "[-l use LENGTH instead of END] [-s Real subs instead of autogenerated] URL START (END|LENGTH)"
            ;;
        *)
            pushd /tmp
            if [ "$localsubs" != "" ]; then
                echo "Real subs"
                youtube-dl --write-sub --sub-lang en --no-continue $URL -o tmp_vid.mp4 -f mp4
            else
                echo "Auto generated subs"
                youtube-dl --write-auto-sub --no-continue $URL -o tmp_vid.mp4 -f mp4
                python3 $HOME/.zsh-scripts/clean_youtube_dl_auto_subs.py tmp_vid.en.vtt > tmp_vid.vtt;
            fi
            echo "LENGHT" $ffmpeg_length;
            if [ "$ffmpeg_length" != ""]; then
                echo "Length based ffmpeg"
                ffmpeg -ss $START -i tmp_vid.mp4 -t $END_OR_LENGTH -vf subtitles=tmp_vid.vtt:force_style='FontSize=40' -c:v libx264 -x264-params crf=22 -preset fast -profile:v high tmp_vid_out.mp4
            else
                echo "Timestamp based ffmpeg"
                ffmpeg -i tmp_vid.mp4 -ss $START -to $END_OR_LENGTH -vf subtitles=tmp_vid.vtt:force_style='FontSize=40' -c:v libx264 -x264-params crf=22 -preset fast -profile:v high tmp_vid_out.mp4
            fi
            mv tmp_vid_out.mp4 tmp_vid.mp4
            clip-file tmp_vid.mp4
            notify-send "Youtube clip created $START to $END_OR_LENGTH"
            popd
            ;;
    esac
}

cut-tmp-video(){
    pushd /tmp
    ffmpeg  -ss $1 -i tmp_vid.mp4 -to $2 -c copy tmp_vid_out.mp4
    mv tmp_vid_out.mp4 tmp_vid.mp4
    clip-file tmp_vid.mp4
    notify-send "Youtube clip created $1 to $2"
    popd
}
